import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Heading from "./components/Heading";
import Navbar from "./components/Navbar";
import Layout from "./components/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Cebu Costume Avenue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Layout>
        <Heading title="Browse our products!" size="text-3xl" />
      </Layout>
    </>
  );
}
